# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - avans-programmeren-4

on:
    push:
        branches:
            - release
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: npm install, build, and test
              run: |
                  npm install

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: release.zip

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Run tests
              run: npm test

    integrationtests:
        runs-on: ubuntu-latest
        needs: build
        env:
            MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: share_a_meal
            DB_USER: root
            DB_PASSWORD: root
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Start MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_DATABASE}};"

            - name: Import the database
              run: |
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} < share-a-meal.sql
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} -e "SHOW TABLES;"

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_DATABASE --DB_PORT $DB_PORT

    deploy:
        runs-on: ubuntu-latest
        needs: [integrationtests]
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1BBE1C6E15343998BFC3645A680ED2B }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E4B3675A0364996820873E3FA4F60EE }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F3DEA5E24B3342A78C09701C708835A9 }}

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'avans-programmeren-4'
                  slot-name: 'Production'
                  package: .
